name: Cypress Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore